import Head from "next/head";
import Link from "next/link";
import { FcGoogle } from "react-icons/fc";
import { MdArrowBack } from "react-icons/md";
import styles from "@/styles/pages/Login.module.scss";
import { useState } from "react";
import { useRouter } from "next/router";

const Register = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Login | eChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className={`d-flex justify-content-center ${styles.allForm}`}>
            <div className={styles.wrapper}>
              <div>
                <MdArrowBack
                  onClick={() => router.back()}
                  style={{ width: "25px", height: "25px" }}
                />
                <h3
                  className="text-center"
                  style={{ fontSize: "30px", marginBottom: "20px" }}
                >
                  Login
                </h3>
                <hr className="mb-3" />
              </div>

              {isSuccess && (
                <div className="alert alert-success shadow-lg">
                  <div>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="stroke-current flex-shrink-0 h-6 w-6"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                      />
                    </svg>
                    <span>Login successful! Please wait</span>
                  </div>
                </div>
              )}

              {!isSuccess && (
                <div className="alert alert-error shadow-lg">
                  <div>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="stroke-current flex-shrink-0 h-6 w-6"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
                      />
                    </svg>
                    <span>Error! Task failed successfully.</span>
                  </div>
                </div>
              )}

              <div>
                <div className="mb-3">
                  <label className="form-label">Email address</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Type your email"
                  />
                </div>
                <div className="mb-4">
                  <label className="form-label">Password</label>
                  <input
                    type="password"
                    className="form-control"
                    placeholder="Type your new password"
                  />
                </div>
                <div>
                  <button
                    type="submit"
                    className={`btn btn-primary ${styles.loginButton}`}
                    onClick={() => {
                      setIsSuccess(true);
                    }}
                  >
                    Login
                  </button>
                  <p className="mt-3 mb-3 text-center">Or login with</p>
                  <button
                    type="submit"
                    className={`btn ${styles.googleButton}`}
                    onClick={() => {
                      setIsSuccess(false);
                    }}
                  >
                    <FcGoogle className="me-2" />
                    Google
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Register;
