/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Register = () => {
  const router = useRouter();

  useEffect(() => {
    const isLogin = localStorage.getItem("user");
    if (isLogin) {
      router.replace("/");
    }
  }, []);

  return (
    <>
      <Head>
        <title>eChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div
            className="d-flex justify-content-center"
            style={{ height: "100vh", alignItems: "center" }}
          >
            <div
              style={{
                background: "#FFFFFF",
                width: "31%",
                padding: "26px",
                borderRadius: "8px",
              }}
            >
              <div className="d-flex justify-content-center">
                <img
                  src="/images/echat-logo.png"
                  style={{ width: "27%" }}
                  alt="logo"
                />
              </div>
              <div>
                <div>
                  <h6 className="text-center mt-4">
                    Welcome to eChat! <br /> Please select an option below
                  </h6>
                </div>
                <div>
                  <Link href="/auth/register">
                    <button
                      type="submit"
                      className="btn btn-primary mt-3"
                      style={{ width: "100%", borderRadius: "20px" }}
                    >
                      Register
                    </button>
                  </Link>
                  <p className="text-center mb-3 mt-3">Or</p>
                  <Link href="/auth/login">
                    <button
                      type="submit"
                      className="btn btn-primary"
                      style={{ width: "100%", borderRadius: "20px" }}
                    >
                      Login
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Register;
