import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/pages/Home.module.scss";
import {
  Grid,
  InputAdornment,
  List,
  ListItem,
  ListItemAvatar,
  Avatar,
  TextField,
  Typography,
  ListItemText,
} from "@mui/material";
import { Container } from "@mui/system";

const Home = () => {
  const [isClicked, setIsClicked] = useState(false);

  return (
    <>
      <Head>
        <title>eChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container height="100vh">
          <Grid
            item
            lg={4}
            sx={{
              boxShadow: "2px 2px 5px 0px rgba(0,0,0,0.75)",
              background: "linear-gradient(#B30000 21.8%, #FFFFFF 10%);",
            }}
          >
            <Container sx={{ pt: "15px" }}>
              <Typography variant="h2" className={styles.textLogo}>
                eChat
              </Typography>
              <TextField
                id="outlined-basic"
                placeholder="Search or start new chat"
                variant="outlined"
                fullWidth
                size="small"
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <img src="/images/search.svg" />
                    </InputAdornment>
                  ),
                }}
                sx={{
                  my: "20px",
                  backgroundColor: "white",
                  borderRadius: "5px",
                }}
              />

              <List className={styles.listChats}>
                {[...new Array(15)].map((item, key) => (
                  <ListItem
                    alignItems="flex-start"
                    sx={{ paddingLeft: "0px" }}
                    button
                    key={key}
                  >
                    <ListItemAvatar>
                      <Avatar alt="Xavier" src="/static/images/avatar/1" />
                    </ListItemAvatar>
                    <ListItemText
                      primary="Charles Xavier"
                      secondary={
                        <Typography
                          sx={{ display: "inline" }}
                          component="span"
                          variant="body2"
                          color="text.primary"
                        >
                          Hello Doctor
                        </Typography>
                      }
                    />
                  </ListItem>
                ))}
              </List>
            </Container>
          </Grid>
          <Grid item-lg={8}>
            <Typography className={styles.rightSideSlogan}>
              Please select a chat to start messaging
            </Typography>
          </Grid>
        </Grid>
      </main>
    </>
  );
};

export default Home;
