import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { FcGoogle } from "react-icons/fc";
import { MdArrowBack } from "react-icons/md";
import styles from "@/styles/pages/Register.module.scss";
import { useRouter } from "next/router";

const Register = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Register | eChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className={`d-flex justify-content-center ${styles.allForm}`}>
            <div className={styles.wrapper}>
              <div>
                <MdArrowBack onClick={() => router.back()} />
                <h3 className="text-center">Register</h3>
                <hr />
              </div>
              <div>
                <div className="mt-4 mb-3">
                  <label className="form-label">Name</label>
                  <input
                    type="email"
                    className="form-control"
                    placeholder="Type your name"
                  />
                </div>
                <div className="mb-3">
                  <label className="form-label">Email address</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Type your email"
                  />
                </div>
                {/* <div className="mb-3">
                  <label className="form-label">Phone Number</label>
                  <input
                    type="tel"
                    className="form-control"
                    placeholder="Type your phone number"
                  />
                </div> */}
                <div className="mb-4">
                  <label className="form-label">Password</label>
                  <input
                    type="password"
                    className="form-control"
                    placeholder="Type your new password"
                  />
                </div>
                <div>
                  <button
                    type="submit"
                    className={`btn btn-primary ${styles.registerButton}`}
                  >
                    Register
                  </button>
                  <p className="mt-3 mb-3 text-center">Or register with</p>
                  <button
                    type="submit"
                    className={`btn ${styles.googleButton}`}
                  >
                    <FcGoogle className="me-2" />
                    Google
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Register;
